### ISSUE TITLE
google.query is not a function 

### ISSUE THREAD

**Issue by RajNextgentm** [simov/purest#33]
TypeError: google.query is not a function
    at module.exports (C:\Users\Torakami\Documents\GitHub\lootmogul\gameplatform-cms\src\extensions\users-permissions\services\providers-list.js:118:10)
    at getProfile (C:\Users\Torakami\Documents\GitHub\lootmogul\gameplatform-cms\src\extensions\users-permissions\services\providers.js:38:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)

**Comment by simov** [comment]
Can't really tell without seeing your code.

**Comment by simov** [comment]
Feel free to re-open the issue if you have additional info to share.
