### ISSUE TITLE
Example doesn't run

### ISSUE THREAD

**Issue by vanjan** [simov/purest#4]
I'm getting the following error trying to run the example:
```
$ node app.js 
module.js:338
    throw err;
          ^
Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jan/dev/projects/purest/lib/provider.js:2:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```
```
$ node --version
v0.12.2
```
```
$ npm --version
2.7.5
```

**Comment by simov** [comment]
`npm install` ?

**Comment by vanjan** [comment]
yeah, that was after a `npm install`

**Comment by simov** [comment]
For some reason you don't have `request` installed in `purest/node_modules` if you cloned the repo, you have to enter the `purest` folder and `npm install`

**Comment by vanjan** [comment]
ah, I ran `npm install` in `example`, but not in the root

**Comment by simov** [comment]
Yep, I guess that's misleading. I plan on improving a couple of things around this project. Also note that some of the examples require additional input parameters to run ... long story short - some of them won't run :)
